name: CI

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  test:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        ts-version: [4.4.x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} & Typescript ${{ matrix.ts-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn install
          yarn add typescript@${{ matrix.ts-version }} --dev
      - run: yarn test
      - name: Coverage
        uses: codecov/codecov-action@v1
        if: matrix.node-version == '14.x' && matrix.ts-version == '4.4.x' && github.ref == 'refs/heads/master'
  publish:
    if: "!contains(toJson(github.event.commits), '[skip ci]')"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
